server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey : "McbPScwq5ohQ1ucCX1cD67AUfGTW49RHUm0BaEzMd3/9zXBa7h6LE4jgP1FpOqyi"
  valid-duration: 3600 #in second
  refreshable-duration: 4000 #in seconds